// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Migration'ları doğrulamak/diff almak için Prisma'nın geçici olarak
    // oluşturup düşürdüğü veritabanı. Sadece geliştirme CLI'ında kullanılır;
    // `migrate deploy` (production) buna ihtiyaç duymaz.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
